import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { Toaster } from 'react-hot-toast';
import Navbar from "@/components/Navbar";
import { Orbitron } from 'next/font/google';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['600', '800'],
  variable: '--font-orbitron',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}${orbitron.variable} antialiased`}>
        <Navbar />
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
